use std::collections::BTreeMap;
use crate::{ParameterHandle, Tensor, WeightSetError, WeightSetManager};
use super::transformer::ExternalTransformer;

#[derive(Clone, Debug)]
pub struct TransformerTrainReport { pub loss_before:f32, pub loss_after:f32, pub gradient_l2:f32, pub changed_tensors:usize }

#[derive(Clone)]
struct LayerCache { layer:usize, input:Tensor, norm1:Tensor, q:Tensor, k:Tensor, v:Tensor, attn:Tensor, probs:Vec<Vec<f32>>, residual:Tensor, norm2:Tensor, gate:Tensor, up:Tensor, silu_gate:Tensor, mlp:Tensor, output:Tensor, q_w:Tensor, k_w:Tensor, v_w:Tensor, o_w:Tensor, gate_w:Tensor, up_w:Tensor, down_w:Tensor, norm1_w:Tensor, norm2_w:Tensor }
struct ForwardCache { tokens:Vec<usize>, embedding:Tensor, layers:Vec<LayerCache>, final_input:Tensor, final_norm:Tensor, final_norm_w:Tensor, lm_head:Tensor, logits:Tensor }

fn handle(model:&ExternalTransformer,name:impl Into<String>)->Result<ParameterHandle,WeightSetError>{ParameterHandle::new(model.weight_set.clone(),name)}
fn read(model:&ExternalTransformer,manager:&WeightSetManager,name:impl Into<String>)->Result<Tensor,WeightSetError>{handle(model,name)?.read(manager)}
fn transpose(x:&Tensor)->Result<Tensor,WeightSetError>{let(r,c)=(x.shape()[0],x.shape()[1]);let mut o=vec![0.0;r*c];for i in 0..r{for j in 0..c{o[j*r+i]=x.values()[i*c+j];}}Tensor::from_vec(vec![c,r],o)}
fn mm(a:&Tensor,b:&Tensor)->Result<Tensor,WeightSetError>{a.matmul(b)}
fn norm_fwd(x:&Tensor,w:&Tensor,eps:f32)->Result<Tensor,WeightSetError>{let(s,h)=(x.shape()[0],x.shape()[1]);let mut o=vec![0.0;s*h];for r in 0..s{let off=r*h;let mut ms=0.0;for d in 0..h{let v=x.values()[off+d];ms+=v*v;}let inv=(ms/h as f32+eps).sqrt().recip();for d in 0..h{o[off+d]=x.values()[off+d]*inv*w.values()[d];}}Tensor::from_vec(vec![s,h],o)}
fn norm_bwd(x:&Tensor,w:&Tensor,dy:&Tensor,eps:f32)->Result<(Tensor,Tensor),WeightSetError>{let(s,h)=(x.shape()[0],x.shape()[1]);let mut dx=vec![0.0;s*h];let mut dw=vec![0.0;h];for r in 0..s{let off=r*h;let mut ms=0.0;for d in 0..h{let v=x.values()[off+d];ms+=v*v;}let inv=(ms/h as f32+eps).sqrt().recip();let mut t=0.0;for d in 0..h{t+=dy.values()[off+d]*w.values()[d]*x.values()[off+d];dw[d]+=dy.values()[off+d]*x.values()[off+d]*inv;}let coeff=inv*inv*t/h as f32;for d in 0..h{dx[off+d]=w.values()[d]*inv*(dy.values()[off+d]-x.values()[off+d]*coeff);}}Ok((Tensor::from_vec(vec![s,h],dx)?,Tensor::from_vec(vec![h],dw)?))}
fn silu(x:f32)->f32{x/(1.0+(-x).exp())}
fn dsilu(x:f32)->f32{let s=1.0/(1.0+(-x).exp());s+x*s*(1.0-s)}
fn attention_fwd(q:&Tensor,k:&Tensor,v:&Tensor)->Result<(Tensor,Vec<Vec<f32>>),WeightSetError>{let(s,h)=(q.shape()[0],q.shape()[1]);let scale=(h as f32).sqrt();let mut o=vec![0.0;s*h];let mut ps=Vec::with_capacity(s);for i in 0..s{let mut sc=Vec::with_capacity(i+1);for j in 0..=i{let mut dot=0.0;for d in 0..h{dot+=q.values()[i*h+d]*k.values()[j*h+d];}sc.push(dot/scale);}let m=sc.iter().copied().fold(f32::NEG_INFINITY,f32::max);let mut p:Vec<f32>=sc.iter().map(|x|(x-m).exp()).collect();let z:f32=p.iter().sum();for a in &mut p{*a/=z.max(f32::MIN_POSITIVE);}for(j,a)in p.iter().enumerate(){for d in 0..h{o[i*h+d]+=*a*v.values()[j*h+d];}}ps.push(p);}Ok((Tensor::from_vec(vec![s,h],o)?,ps))}
fn attention_bwd(q:&Tensor,k:&Tensor,v:&Tensor,p:&[Vec<f32>],dy:&Tensor)->Result<(Tensor,Tensor,Tensor),WeightSetError>{let(s,h)=(q.shape()[0],q.shape()[1]);let scale=(h as f32).sqrt();let mut dq=vec![0.0;s*h];let mut dk=vec![0.0;s*h];let mut dv=vec![0.0;s*h];for i in 0..s{let pi=&p[i];let mut dp=vec![0.0;pi.len()];for j in 0..pi.len(){for d in 0..h{dp[j]+=dy.values()[i*h+d]*v.values()[j*h+d];dv[j*h+d]+=pi[j]*dy.values()[i*h+d];}}let mut dot=0.0;for j in 0..pi.len(){dot+=pi[j]*dp[j];}for j in 0..pi.len(){let ds=pi[j]*(dp[j]-dot);for d in 0..h{dq[i*h+d]+=ds*k.values()[j*h+d]/scale;dk[j*h+d]+=ds*q.values()[i*h+d]/scale;}}}Ok((Tensor::from_vec(vec![s,h],dq)?,Tensor::from_vec(vec![s,h],dk)?,Tensor::from_vec(vec![s,h],dv)?))}
fn ce(logits:&Tensor,target:usize)->Result<(f32,Tensor),WeightSetError>{let(s,v)=(logits.shape()[0],logits.shape()[1]);let row=&logits.values()[(s-1)*v..s*v];let m=row.iter().copied().fold(f32::NEG_INFINITY,f32::max);let mut e=Vec::with_capacity(v);for x in row{e.push((*x-m).exp());}let z:f32=e.iter().sum();let p=(e[target]/z.max(f32::MIN_POSITIVE)).max(1e-12);let mut g=vec![0.0;s*v];for j in 0..v{g[(s-1)*v+j]=e[j]/z.max(f32::MIN_POSITIVE);}g[(s-1)*v+target]-=1.0;Ok((-p.ln(),Tensor::from_vec(vec![s,v],g)?))}
fn matmul_bwd(x:&Tensor,w:&Tensor,dy:&Tensor)->Result<(Tensor,Tensor),WeightSetError>{Ok((mm(dy,&transpose(w)?)?,mm(&transpose(x)?,dy)?))}
fn add_map(m:&mut BTreeMap<String,Vec<f32>>,name:String,g:&Tensor){let slot=m.entry(name).or_insert_with(||vec![0.0;g.values().len()]);for(i,v)in g.values().iter().enumerate(){slot[i]+=*v;}}
fn cache(model:&ExternalTransformer,manager:&WeightSetManager,tokens:&[usize])->Result<ForwardCache,WeightSetError>{let embedding=model.embedding(manager,tokens)?;let mut hidden=embedding.clone();let mut layers=Vec::with_capacity(model.config.num_layers);for layer in 0..model.config.num_layers{let p=format!("model.layers.{layer:02}");let norm1_w=read(model,manager,format!("{p}.attention_norm.weight"))?;let norm1=norm_fwd(&hidden,&norm1_w,model.config.rms_norm_eps)?;let q_w=read(model,manager,format!("{p}.attention.q_proj.weight"))?;let k_w=read(model,manager,format!("{p}.attention.k_proj.weight"))?;let v_w=read(model,manager,format!("{p}.attention.v_proj.weight"))?;let o_w=read(model,manager,format!("{p}.attention.o_proj.weight"))?;let q=mm(&norm1,&q_w)?;let k=mm(&norm1,&k_w)?;let v=mm(&norm1,&v_w)?;let(attn,probs)=attention_fwd(&q,&k,&v)?;let projected=mm(&attn,&o_w)?;let residual=hidden.add(&projected)?;let norm2_w=read(model,manager,format!("{p}.mlp_norm.weight"))?;let norm2=norm_fwd(&residual,&norm2_w,model.config.rms_norm_eps)?;let gate_w=read(model,manager,format!("{p}.mlp.gate_proj.weight"))?;let up_w=read(model,manager,format!("{p}.mlp.up_proj.weight"))?;let down_w=read(model,manager,format!("{p}.mlp.down_proj.weight"))?;let gate=mm(&norm2,&gate_w)?;let up=mm(&norm2,&up_w)?;let sg=Tensor::from_vec(gate.shape().to_vec(),gate.values().iter().map(|x|silu(*x)).collect())?;let mlp=sg.hadamard(&up)?;let down=mm(&mlp,&down_w)?;let output=residual.add(&down)?;layers.push(LayerCache{layer,input:hidden.clone(),norm1,q,k,v,attn,probs,residual:residual.clone(),norm2,gate,up,silu_gate:sg,mlp,output:output.clone(),q_w,k_w,v_w,o_w,gate_w,up_w,down_w,norm1_w,norm2_w});hidden=output;}let final_norm_w=read(model,manager,"model.final_norm.weight")?;let final_input=hidden.clone();let final_norm=norm_fwd(&final_input,&final_norm_w,model.config.rms_norm_eps)?;let lm_head=read(model,manager,"model.lm_head.weight")?;let logits=mm(&final_norm,&transpose(&lm_head)?)?;Ok(ForwardCache{tokens:tokens.to_vec(),embedding,layers,final_input,final_norm,final_norm_w,lm_head,logits})}

pub fn train_step_ce(model:&ExternalTransformer,manager:&mut WeightSetManager,tokens:&[usize],target:usize,lr:f32)->Result<TransformerTrainReport,WeightSetError>{let before=cache(model,manager,tokens)?;let(loss,dlog)=ce(&before.logits,target)?;let lm_t=transpose(&before.lm_head)?;let(d_final,d_lm_t)=matmul_bwd(&before.final_norm,&lm_t,&dlog)?;let d_lm=transpose(&d_lm_t)?;let mut grads=BTreeMap::<String,Vec<f32>>::new();add_map(&mut grads,"model.lm_head.weight".into(),&d_lm);let(mut dh,dfw)=norm_bwd(&before.final_input,&before.final_norm_w,&d_final,model.config.rms_norm_eps)?;add_map(&mut grads,"model.final_norm.weight".into(),&dfw);for l in before.layers.iter().rev(){let p=format!("model.layers.{:02}",l.layer);let(dmlp,ddown)=matmul_bwd(&l.mlp,&l.down_w,&dh)?;add_map(&mut grads,format!("{p}.mlp.down_proj.weight"),&ddown);let mut dsg=vec![0.0;l.mlp.values().len()];let mut dup=vec![0.0;l.mlp.values().len()];for i in 0..dsg.len(){dsg[i]=dmlp.values()[i]*l.up.values()[i];dup[i]=dmlp.values()[i]*l.silu_gate.values()[i];}let dg=Tensor::from_vec(l.gate.shape().to_vec(),(0..dsg.len()).map(|i|dsg[i]*dsilu(l.gate.values()[i])).collect())?;let du=Tensor::from_vec(l.up.shape().to_vec(),dup)?;let(dn2a,dgw)=matmul_bwd(&l.norm2,&l.gate_w,&dg)?;let(dn2b,duw)=matmul_bwd(&l.norm2,&l.up_w,&du)?;add_map(&mut grads,format!("{p}.mlp.gate_proj.weight"),&dgw);add_map(&mut grads,format!("{p}.mlp.up_proj.weight"),&duw);let mut dn2=vec![0.0;dn2a.values().len()];for i in 0..dn2.len(){dn2[i]=dn2a.values()[i]+dn2b.values()[i];}let dn2=Tensor::from_vec(l.norm2.shape().to_vec(),dn2)?;let(dr2,dn2w)=norm_bwd(&l.residual,&l.norm2_w,&dn2,model.config.rms_norm_eps)?;add_map(&mut grads,format!("{p}.mlp_norm.weight"),&dn2w);let dr=dh.add(&dr2)?;let(dattn,dow)=matmul_bwd(&l.attn,&l.o_w,&dr)?;add_map(&mut grads,format!("{p}.attention.o_proj.weight"),&dow);let(dq,dk,dv)=attention_bwd(&l.q,&l.k,&l.v,&l.probs,&dattn)?;let(dnq,dqw)=matmul_bwd(&l.norm1,&l.q_w,&dq)?;let(dnk,dkw)=matmul_bwd(&l.norm1,&l.k_w,&dk)?;let(dnv,dvw)=matmul_bwd(&l.norm1,&l.v_w,&dv)?;add_map(&mut grads,format!("{p}.attention.q_proj.weight"),&dqw);add_map(&mut grads,format!("{p}.attention.k_proj.weight"),&dkw);add_map(&mut grads,format!("{p}.attention.v_proj.weight"),&dvw);let mut dn1=vec![0.0;dnq.values().len()];for i in 0..dn1.len(){dn1[i]=dnq.values()[i]+dnk.values()[i]+dnv.values()[i];}let dn1=Tensor::from_vec(l.norm1.shape().to_vec(),dn1)?;let(din,dn1w)=norm_bwd(&l.input,&l.norm1_w,&dn1,model.config.rms_norm_eps)?;add_map(&mut grads,format!("{p}.attention_norm.weight"),&dn1w);dh=dr.add(&din)?;}
    let h=model.config.hidden_size;let mut eg=vec![0.0;model.config.vocab_size*h];for(row,tok)in before.tokens.iter().enumerate(){for d in 0..h{eg[tok*h+d]+=dh.values()[row*h+d];}}add_map(&mut grads,"model.embeddings.token.weight".into(),&Tensor::from_vec(vec![model.config.vocab_size,h],eg)?);
    let mut g2=0.0;let mut changed=0;for(name,g)in grads{g2+=g.iter().map(|x|x*x).sum::<f32>();if g.iter().any(|x|x.abs()>1e-12){changed+=1;}let h=handle(model,name)?;let mut w=h.read(manager)?;for(i,gg)in g.iter().enumerate(){w.values_mut()[i]-=lr*gg;}h.write(manager,&w)?;}let after=cache(model,manager,tokens)?;let(loss_after,_)=ce(&after.logits,target)?;Ok(TransformerTrainReport{loss_before:loss,loss_after,gradient_l2:g2.sqrt(),changed_tensors:changed})}
